version: '3'
services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432  # make sure you don't have another container running on 5432

    environment:
      - POSTGRES_DB=chatbotDB
      - POSTGRES_USER=chandan
      - POSTGRES_PASSWORD=Chandan@143

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080